
export const catagoryConstants = {
    CATAGORY_LIST_REQUEST: 'CATAGORY_LIST_REQUEST',
    CATAGORY_LIST_SUCCESS: 'CATAGORY_LIST_SUCCESS',
    CATAGORY_LIST_FAILURE: 'CATAGORY_LIST_FAILURE',
    CREATE_CATAGORY_REQUEST: 'CREATE_CATAGORY_REQUEST',
    CREATE_CATAGORY_SUCCESS: 'CREATE_CATAGORY_SUCCESS',
    CREATE_CATAGORY_FAILURE: 'CREATE_CATAGORY_FAILURE',
}
export const productConstants = {
    PRODUCTS_BY_SLUG_REQUEST: 'PRODUCTS_BY_SLUG',
    PRODUCTS_BY_SLUG_SUCCESS: 'PRODUCTS_BY_SLUG_SUCCESS',
    PRODUCTS_BY_SLUG_FAILURE: 'PRODUCTS_BY_SLUG_FAILURE',
    PRODUCT_BY_SLUG_PAGE_REAL_REQUEST: 'PRODUCT_BY_SLUG_PAGE_REAL_REQUEST',
    PRODUCT_BY_SLUG_PAGE_REAL_SUCCESS: 'PRODUCT_BY_SLUG_PAGE_REAL_SUCCESS',
    PRODUCT_BY_SLUG_PAGE_REAL_FAILURE: 'PRODUCT_BY_SLUG_PAGE_REAL_FAILURE',
    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAILURE: 'PRODUCT_DETAIL_FAILURE',
}
export const authConstants = {
    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
}
export const cartConstants = {
    ADD_TO_CART: 'ADD_TO_CART',
    KEEP_CART_ADDED: 'KEEP_CART_ADDED',
    INCREMENT_CART_ITEM: 'INCREMENT_CART_ITEM',
    DECREMENT_CART_ITEM: 'DECREMENT_CART_ITEM',
    LOGGED_IN_USER_CARTITEMS_REQUEST: 'LOGGED_IN_USER_CARTITEMS_REQUEST',
    LOGGED_IN_USER_CARTITEMS_SUCCESS: 'LOGGED_IN_USER_CARTITEMS_SUCCESS',
    LOGGED_IN_USER_CARTITEMS_FAILURE: 'LOGGED_IN_USER_CARTITEMS_FAILURE',
    LOGGED_IN_USER_GET_ALL_CART_ITEMS_REQUEST: 'LOGGED_IN_USER_GET_ALL_CART_ITEMS_REQUEST',
    LOGGED_IN_USER_GET_ALL_CART_ITEMS_SUCCESS: 'LOGGED_IN_USER_GET_ALL_CART_ITEMS_SUCCESS',
    LOGGED_IN_USER_GET_ALL_CART_ITEMS_FAILURE: 'LOGGED_IN_USER_GET_ALL_CART_ITEMS_FAILURE',
    LOGGED_IN_USER_ADD_TO_CART_REQUEST: 'LOGGED_IN_USER_ADD_TO_CART_REQUEST',
    LOGGED_IN_USER_ADD_TO_CART_SUCCESS: 'LOGGED_IN_USER_ADD_TO_CART_SUCCESS',
    LOGGED_IN_USER_ADD_TO_CART_FAILURE: 'LOGGED_IN_USER_ADD_TO_CART_FAILURE',
    RESET_CART: "RESET_CART",
}

export const addressConstants = {
    GET_ADDRESS_REQUEST: 'GET_ADDRESS_REQUEST',
    GET_ADDRESS_SUCCESS: 'GET_ADDRESS_SUCCESS',
    GET_ADDRESS_FAILURE: 'GET_ADDRESS_FAILURE',
    UPDATE_ADDRESS_REQUEST: 'UPDATE_ADDRESS_REQUEST',
    UPDATE_ADDRESS_SUCCESS: 'UPDATE_ADDRESS_SUCCESS',
    UPDATE_ADDRESS_FAILURE: "UPDATE_ADDRESS_FAILURE",
}


export const orderConstants = {
    GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',
    GET_ORDER_DETAIL_PAGE_REQUEST: 'GET_ORDER_DETAIL_PAGE_REQUEST',
    GET_ORDER_DETAIL_PAGE_SUCCESS: 'GET_ORDER_DETAIL_PAGE_SUCCESS',
    GET_ORDER_DETAIL_PAGE_FAILURE: 'GET_ORDER_DETAIL_PAGE_FAILURE',
}


